### ISSUE TITLE
material: integration of shiny

### ISSUE THREAD

**Issue by MiWebR** [juba/rmdformats#55] opened 2019-04-05 09:56 UTC
I got some problems with using the material template and embedded shiny applications together. I´m using the material.Rmd example.

When using the usual preamble chunk

```
---
title: "Sample document"
output:
  rmdformats::material:
    highlight: kate
    self_contained: true
    code_folding: show
    thumbnails: true
    gallery: true
    fig_width: 4
    fig_height: 4
    df_print: kable
---
```
everything works fine:

![image](https://user-images.githubusercontent.com/49305812/55619360-cf88b800-5798-11e9-87f0-91d749c86e8b.png)

 But when I just integrate "runtime: shiny" (even without integrating an actual shiny app)
```
---
title: "Sample document"
output:
  rmdformats::material:
    highlight: kate
    self_contained: true
    code_folding: show
    thumbnails: true
    gallery: true
    fig_width: 4
    fig_height: 4
    df_print: kable
runtime: shiny
---
```
the design get´s destroyed and the table of content on the left isn´t working anymore:

![image](https://user-images.githubusercontent.com/49305812/55619482-0c54af00-5799-11e9-8100-4cb5a3a46a2d.png)

My session.Info():

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       bookdown_0.9     digest_0.6.18    later_0.8.0      mime_0.6         R6_2.4.0         xtable_1.8-3     magrittr_1.5     evaluate_0.13   
[10] rmdformats_0.3.5 highr_0.7        rstudioapi_0.9.0 promises_1.0.1   miniUI_0.1.1.1   rmarkdown_1.12   tools_3.5.2      questionr_0.7.0  shiny_1.2.0     
[19] httpuv_1.5.0     xfun_0.5         yaml_2.2.0       compiler_3.5.2   htmltools_0.3.6  knitr_1.22
```

**Comment by juba** [comment] 2019-04-10 09:45
You're right, `material` is broken when using `runtime: shiny`. This is due to the fact that a bit of JavaScript is run to setup the document, at startup, and when using `runtime: shiny` the document is not show immediately...

I'm looking for a way to fix this.

**Comment by juba** [comment] 2019-04-10 10:10
This should now be fixed in the development version. Thanks for taking the time to report the problem.

**Comment by MiWebR** [comment] 2019-04-10 14:31
Thanks for taking care of the issue so fast! Sadly I encountered some more issues when using the new development version which are a little harder to explain, but I will try.

When first using it today, everything looked fine, because the design didn´t get destroyed any more. But it seems like it only works for shiny applications which are included in the first chapter, where it looks and works like you would expect it:

![image](https://user-images.githubusercontent.com/49305812/55886729-91323500-5bac-11e9-9fb5-024d93b104e1.png)

The plot changes when I change the number of bins or the bandwith. But when I include the same shiny app in any other chapter, there are two different problems:

- When I use the RStudio Viewer (after just clicking "Run Document" in RStudio), the plot is rendered, but it doesn´t react to changes of the input-parameters anymore
- When I use the Browser (after clicking "Open in Browser" in the Viewer), the shiny app on the first page still works properly, but the plot on the other pages/chapters isn´t even rendered anymore:

![image](https://user-images.githubusercontent.com/49305812/55887197-61376180-5bad-11e9-9087-42268bc1c8a0.png)

Please note additionally, that the chapter change in the table of contents isn´t highlighted correctly anymore, because the highlighting doesn´t change to the chapter "Tables".

I hope the problem got clear and that you have an idea how to fix it. Because the material template is absolutely perfect and if the shiny integration would work correctly, it would be really really great!

Thanks in advance!

**Comment by MiWebR** [comment] 2019-04-10 14:42
Small addition - this is how I included the shiny-apps:

```
selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)

renderPlot({
  hist(faithful$eruptions, probability = TRUE,
       breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)",
       main = "Geyser eruption duration")

  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

**Comment by juba** [comment] 2019-04-11 09:49
Yes, I can reproduce this.

There must be a weird interaction between the JavaScript used in the template and the one used in Shiny. But I'm a bit confused for now as there is absolutely no error message either in R or in the JS console.

I'll take a deeper look into it when I can...

**Comment by MiWebR** [comment] 2019-04-11 09:51
Great, thank you very much!

**Closed** 2019-05-02 10:04 UTC

**Comment by juba** [comment] 2019-05-02 10:06
I think this issue is now closed. However, it is possible that other problems may arise linked to JavaScript interactions and timing issues when using Shiny inside documents. Don't hesitate to reopen the issue or to create a new one if needed.

**Comment by mkaranja** [comment] 2019-08-22 13:56
I have developed a user manual using this design. It is accessible as a link on tabPanel in shiny app. First it opens fine, but when I click on sidebar headers to browse to specific title, it takes me back to the shiny app.
Thanks,
Margaret

**Comment by juba** [comment] 2019-08-28 08:08
Unfortunaltely I fear I won't be able to take a look at your issue without a reproducible example. I'm not sure I understand how the material-based manual is integrated in your shiny app.

**Comment by mkaranja** [comment] 2019-08-28 08:25
Please see attached shiny app,
User manual is a link in About dropdown menu. It works fine in my local but not on shiny server pro
Thanks
[shiny-rmdformats-material.zip](https://github.com/juba/rmdformats/files/3549874/shiny-rmdformats-material.zip)

**Comment by juba** [comment] 2019-08-28 10:49
Thanks for the reproducible example.

Unfortunately, this problem has nothing to do with `rmdformats` : if you use the standard `html_document` format with `toc: true` you will have the same problem. A workaround should be to put your HTML manual in a folder or server outside of your shiny app, I think.
