### ISSUE TITLE
Dynamic TOC is… well, not dynamic

### ISSUE THREAD

**Issue by jemus42** [juba/rmdformats#6] opened 2016-02-19 16:51 UTC
[Example HTML](http://stats.jemu.name/qm/meta/Teilnehmer.html) – [Source Rmd](http://dump.jemu.name/Teilnehmer.Rmd)

I'm not sure what's going on, and I'd just like to make sure it's not a bug in the template or something.

Thanks!

**Comment by juba** [comment] 2016-02-19 17:20
I've found the cause of the bug : it's due to presence of dots in your heading "Waffles. No seriously.", which causes a javascript error.

Now I just have to find a fix :). I'll take a look at it.

Thanks for reporting.

**Comment by juba** [comment] 2016-02-19 18:36
Ok, so the problem is not relative to `rmdformats` directly. It is caused in the HTML rendering, when HTML ids are generated from the text content of a heading, without replacing the dots, which are illegal in CSS ids.

I have to keep looking for the source of this bug, not sure if it comes from `rmarkdown`, `pandoc` or elsewhere...

**Comment by juba** [comment] 2016-02-19 18:53
Ok, so the problem comes from Pandoc, which keeps periods when generating section identifiers automatically, as explained in the `auto_identifiers` section of [its README](http://pandoc.org/README.html).

It's not a bug per se, so I don't think I'll try to report it to pandoc developers (but you can if you want !). As a workaround, pandoc documentation shows that you can manually specify an identifier when needed, 

If you have the following heading :

    ## Heading. With two periods.

You can specify an id like this :

    ## Heading. With two periods.  {#my-id-without-periods}

So I close the issue for now, let me now if the workaround doesn't work.

**Closed by juba** 2016-02-19 18:53 UTC

**Comment by jemus42** [comment] 2016-02-19 18:57
Wow, thanks a lot for your effort on this! Yes, you can close the issue, I just wanted to make sure it's not a problem with the template. 

Thanks!
