### ISSUE TITLE
`robobook` template does not display TOC correctly when `toc_depth: 4`

### ISSUE THREAD

**Issue by chamaoskurumi** [juba/rmdformats#126] opened 2022-02-18 20:22 UTC
Using `rmdformats::robobook` with `toc_depth: 4` results in a cut off view of the headers of fourth order:

![image](https://user-images.githubusercontent.com/7808560/154755865-845b526c-c0bd-4c10-8438-c63049de9cc0.png)

The yaml header I'm using: 

```Rmd
---
title: "Test"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
    self_contained: true
    toc_depth: 4
---
```

See this [test.Rmd](https://github.com/juba/rmdformats/files/8100131/test.txt)
 minimal working example (you have to rename it to `.Rmd`, Github does not allow uploads of `.Rmd` files)

**Comment by juba** [comment] 2022-02-23 17:52
Hi, and sorry for my late answer.
You're right, `robobook` only supports `toc_depth` <= 2, so your "Fourth  header" item should not appear. This should be fixed now in the development version.

Thanks for taking the time to report the issue, and let me know if the problem is still here.

**Closed** 2022-03-01 14:57 UTC

**Comment by ViniciusBRodrigues** [comment] 2022-03-08 14:19
Hi, I'm having the same issue here. Is there some way to turn around it? Many thanks

**Comment by juba** [comment] 2022-03-08 14:21
Hi, the issue should be solved (ie, only the first two toc levels should be shown) in the development version ?

**Comment by ViniciusBRodrigues** [comment] 2022-03-08 14:35
The two levels is working fine. The package version here is 1.0.3 

https://ibb.co/Br2FRwv

**Comment by juba** [comment] 2022-03-08 14:37
Could you try with the development version ? You can install it with :

```r
install.packages(remotes)  # if necessary
remotes::install_github("juba/rmdformats")
```

**Comment by ViniciusBRodrigues** [comment] 2022-03-08 14:57
The package now is the version 1.0.3.9

The toc depth 3 or 4 is not appearing anymore, only toc until 2.

**Comment by juba** [comment] 2022-03-08 15:07
Yes, unfortunately that's the intended behavior, robobook only supports two levels of toc depth...
