### ISSUE TITLE
Can I make tabsets non-scrolling on activation?

### ISSUE THREAD

**Issue by bersbersbers** [juba/rmdformats#122] opened 2021-11-12 13:46 UTC
I'd like the document to not scroll when clicking a tab - can this be done?

```Rmd
---
output:
   rmdformats::material
---
## H2 {.tabset}
<img height=200>

### H3A
<img height=2000>

### H3B
<img height=2000>
```

This is what I currently have - any time I click H3A or H3B, I have to scroll down again:
![neAGSEwb3k](https://user-images.githubusercontent.com/12128514/141476985-fea16c07-5bc7-48a5-9ac9-72c675bcc342.gif)

**Comment by bersbersbers** [comment] 2021-11-12 13:47
(It would be fine if the body maybe scrolled a bit, but it is scrolling so far I don't even see the header any more.)

**Comment by juba** [comment] 2021-11-12 13:58
Maybe I don't understand correctly, but this problem doesn't seem to occur with a complete document : 

```
---
title: test
output:
   rmdformats::material
---

# Titre 1

## H2 {.tabset}

Hello
<img height=200>

### H3A

Foo 

<img height=2000>

### H3B

Bar

<img height=2000>


# Titre 2

Baz
```

**Comment by bersbersbers** [comment] 2021-11-12 14:05
@juba thanks for your quick response! I can reproduce the same scrolling effect with that full document that you shared. Upon clicking H3A, H3A scrolls so that I cannot see "H3A" any longer. This problem exists in in Chrome 95, but not in IE 11. Maybe you are (one of the few :D) using a different browser than Chrome?

**Comment by bersbersbers** [comment] 2021-11-12 14:06
Ah, behavior in IE11 not completely dissimilar: if you click the *active* tab, then it scrolls up.

But if you click an inactive tab, that tab is selected without scrolling. This is the behavior I'd like in Chrome, too.

**Comment by bersbersbers** [comment] 2021-11-12 14:08
This is IE 11 - see how it is not scrolling when clicking an inactive tab:

![kw9DqDkcBk](https://user-images.githubusercontent.com/12128514/141480006-29d69697-e326-4e77-82c1-212263c76657.gif)

**Comment by juba** [comment] 2021-11-12 15:02
Ah I see, you're right, I got the same behavior in Firefox as in IE11, but when trying in Edge I can see the same thing as you.

Unfortunately I've taken a look but didn't find the culprit for now. It seems to be a weird interaction between Bootstrap and the template JavaScript, but I don't see what exactly. But I'll continue to try to fix it.

**Comment by bersbersbers** [comment] 2021-11-12 15:41
Thanks! If you happened to find/know any hacky way to disable on-click scrolling completely, that would also work for me.

**Comment by juba** [comment] 2021-11-12 15:56
Unfortunately I'm not sure this is possible, because the tabs HTML code is itself produced by JavaScript code, so it is not possible to modify its behavior without modifying the package code itself...

**Comment by bersbersbers** [comment] 2021-11-16 09:43
I wonder if this JS error has something to do with it:

![image](https://user-images.githubusercontent.com/12128514/141960502-e59d7b71-18cf-4298-91ee-f60feb9af603.png)

This is what I get when I open `file:///W:/home/bers/test.html#h3b` directly (note the anchor).

(I can reproduce the original issue, without any error message in the console, using `file:///W:/home/bers/test.html`, so it is not necessarily related.)

**Comment by juba** [comment] 2021-11-16 09:45
Unfortunately no, it is not related. Your issue allowed me to detect this error, and it should be fixed in rmdformats development version, but it doesn't solve your problem...

**Comment by bersbersbers** [comment] 2021-11-16 09:48
I agree - the GitHub version does not have that error, but still has the original issue.

**Comment by bersbersbers** [comment] 2021-11-16 09:52
One weird thing is that Chrome and Firefox behave exactly the opposite. Chrome scrolls on clicking the inactive tab, but not the active one. Firefox scrolls on clicking the active tab, but not the inactive one. I wonder if any of these two behaviors is actually the intended one

**Comment by juba** [comment] 2021-11-16 10:07
Yes, I can confirm that. One thing I just find out is that if you disable the cards behavior with `cards: false`, Edge seems to behave in the same way as Firefox. So there should be a link there.

**Comment by juba** [comment] 2021-11-16 10:23
Ok, I think i finally fixed it ! Could you please test with the development version to see if the problem is solved for you too ?

**Comment by bersbersbers** [comment] 2021-11-16 10:31
Oh, yes!  This looks good! Thanks already! I will test this a bit more, but I is already working in the first full document I tried.

For the record, with 02ce84a82d6f373c69c6d145953abf0cae7fb8ad, the browser location bar no longer updates with tab changes, but I don't actually care about this. (Other people *may*, especially if the deep-link to a specific tab in their document.) But 02ce84a82d6f373c69c6d145953abf0cae7fb8ad very nicely stops all kinds of scrolling FF, Edge and Chrome.

**Comment by juba** [comment] 2021-11-16 10:46
Yes, I noticed that too, but I don't really think it could be a problem, so I think I'll let it like this.

Closing this issue for now, don't hesitate to reopen it if needed. Thanks for your help and patience !

**Closed by juba** 2021-11-16 10:46 UTC
