### ISSUE TITLE
Potential problem with robobook table output  

### ISSUE THREAD

**Issue by octmedina** [juba/rmdformats#91] opened 2021-01-24 12:58 UTC
Hi all!

First of all, thank you for creating `rmdformats`, it's incredibly useful for our work.

I was creating some templates for internal use and ran across a possible issue in the `robobook` template. When using `skimr` to skim a data frame (in this case `penguins`), the html output doesn't adjust the table width to the page size, and the same thing happens if you use `kable`. But then if you change the template and use `readthedown` it seems to work fine.

    ---
    title: "Data Cleaning and Exploration"
    author: "Anonymous"
    date: "The Date"
    output: rmdformats::robobook
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    ```
    
    
    # Importing and cleaning
    
    ```{r message=FALSE, warning=FALSE}
    
    library(palmerpenguins)
    library(skimr)
    library(tidyverse)

    
    data("penguins")
    
    
    ```
    
    ## Taking a look at the data
    
    Let's use the `skimr` package to take an initial look at our data.
    
    ```{r}
    
    penguins %>%
      skim() 
    
    ```
    ```{r}
    
    penguins %>%
      head() %>%
       kableExtra::kable() 
    
    ```

`robobook` output:

![image](https://user-images.githubusercontent.com/44771761/105630827-21557300-5e43-11eb-8ce9-01d40bd4fb47.png)

`readthedown` output:

![image](https://user-images.githubusercontent.com/44771761/105630860-4813a980-5e43-11eb-9df1-403a7688eb3a.png)

Apologies if there's a super obvious solution, I haven't been using this for long! And thank you in advance for your help.

Octavio

**Comment by juba** [comment] 2021-01-25 08:32
Hi,

First, thank you for taking the time to report the issue with a detailed and reproducible example.
You are right, handling of wide tables wasn't good in robobook (and in downcute also). I fix this should be partly fixed in the development version, _ie_ I added horizontal scrollable overflow when the table is wider than the page.

If what you want to achieve is to fully display the table without overflow, I fear you would have to use a custom CSS to adjust tables font sizes and paddings and/or page content width. In `readthedown` I don't think the table output is adjusted to the page width, it's just that the tables are more compact.

Let me know if the issue is still present for you on the development version, and thanks again !

**Closed** 2021-01-25 08:32 UTC

**Comment by octmedina** [comment] 2021-01-25 11:28
Hi Julien!

That makes sense. I just installed the dev version and it works great, the table is scrollable now. Thank you for the super fast response!

Octavio
