### ISSUE TITLE
"runtime: shiny" compatibility

### ISSUE THREAD

**Issue by FlavioLeccese92** [juba/rmdformats#68] opened 2020-02-17 14:35 UTC
I'm experiencing a problem when running a markdown document as a html file with "readthedown" theme (latest version 0.3.6).
When defining a tabset and keeping runtime: shiny in the header, clicking on a tab won't open that tab.
I had not such kind of error so far...
[test.zip](https://github.com/juba/rmdformats/files/4214292/test.zip)

Thank you for your support

**Comment by juba** [comment] 2020-02-17 21:40
Yes, that was caused by an incompatibility with jQuery 3. This should now be fixed in the development version.

Thanks for taking the time to report the problem.

**Closed** 2020-02-17 21:39 UTC
