### ISSUE TITLE
rmdreadthedown reports slow to load

### ISSUE THREAD

**Issue by harrelfe** [juba/rmdformats#76] opened 2020-06-21 16:24 UTC
I'm getting beautiful results with the `readthedown` theme.  The only problem is that `html` files are larger than I used to get with themes that are built-in to `Rmarkdown`, and they are somewhat slow to load.  Is there a way to streamline?

**Comment by juba** [comment] 2020-06-21 20:30
There could be a size and loading time difference due to fonts loading for example, but that should not be very noticeable...

Would you have a sharable example of document with that problem ?

Thanks for taking the time to report the issue.

**Comment by harrelfe** [comment] 2020-06-22 11:18
Here is an example.  Sorry I didn't think to include that up front: https://hbiostat.org/R/hreport/testmult.html

**Comment by juba** [comment] 2020-06-22 13:33
Thanks !

I think the delay is due to the loading of MathJax, which seems to take quite some time. You can test by adding `mathjax: NULL` in the preamble of your document, and see if loading is faster (but then rendering of any TeX/LaTeX would of course be disabled).

I also updated the Mathjax URL in the development version of `rmdformats` to use the one now hosted directly by rstudio. It might be faster than the previous one, but I'm not totally sure. You can test it by installing the development version with :

```r
remotes::install_github("juba/rmdformats")
```

**Comment by harrelfe** [comment] 2020-06-22 16:35
Would you mind giving me the edit I could make in the `html` file instead, to test this?  Thanks.

**Comment by juba** [comment] 2020-06-22 16:44
In the HTML file I think you would have to remove the following block, shortly before the closing `</body>` tag :

```html
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
```

**Comment by harrelfe** [comment] 2020-06-22 18:12
Removing that block did not make it load any faster.  Like before, I first see a page with all the code showing (even though this was not requested).  After a pause, the code is erased and the requested content shows.

**Comment by juba** [comment] 2020-06-22 20:07
Yes, you're right, it clearly is not related to MathJax loading. Sorry it didn't fix the problem,

I can reproduce the issue, so I will investigate further. Thanks again for taking the time to report the problem.

**Comment by juba** [comment] 2020-06-22 20:53
Well, after a bit of tinkering with a local Rmd file, I think the slowness is due to the plotly charts, which can take quite some time to load. This is visible, for example, the first time you switch from the `Study 1` to the `Study 2` tab in the `Accrual` section : on my machine it itakes several seconds to display the second tab.

However, what i can't reproduce is the difference of speed between `readthedown` and the standard `html_document` template : both seem to have about the same load time and the same delay you described during which the code is shown.

If you find the time, do you think you could compile your Rmarkdown with the base `html_document` template and send me the resulting HTML file so that I could compare with the `readthedown` one ?

Thanks.

**Comment by harrelfe** [comment] 2020-06-23 10:51
I should have tested that first.  Here it is: https://hbiostat.org/attach/z.html
The load time does seem to be very similar.  But this `html_document` report is a full megabyte smaller.

**Comment by juba** [comment] 2020-06-23 13:11
Thanks for taking the time to generate an `html_document` version. I don't see quite a difference in loading time either. 

You're right that the `readthedown` version is bigger, I think because it embeds slightly larger CSS and JS files, but mainly because it embeds the custom fonts used in the document. But I'm quite sure the difference in loading time due to the size is not really significant compared to the delay caused by plotly figures...

**Comment by harrelfe** [comment] 2020-06-23 13:40
Thanks for taking the time to deal with this.  For all documents using html widgets it may be worthwhile finding new ways to reduce file sizes.  If you think it's worth limiting the use of custom fonts, any guidance on doing so would be appreciated.  I love the fonts that `readthedown` users but maybe there are built-in fonts that are 0.99 as good?

**Comment by juba** [comment] 2020-06-23 14:06
I just added a new option for `readthedown` in the development version. If you install it and add `embed_fonts: false` in your YAML preamble, fonts should not be embedded in the HTML file anymore...

**Closed** 2020-08-25 15:05 UTC
